# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/lge/sdm845-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter judyp judypn judyln caymanslm style3lm,$(TARGET_DEVICE)),)

endif
